USE master
IF DB_ID (N'MDiSUBD_lab3_task2') IS NOT NULL 
BEGIN
	ALTER DATABASE MDiSUBD_lab3_task2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE MDiSUBD_lab3_task2;
END;
GO

CREATE DATABASE MDiSUBD_lab3_task2
GO

USE MDiSUBD_lab3_task2;
GO

CREATE TABLE Faculty 
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL UNIQUE,
);
GO

CREATE TABLE GROUPS 
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL,
	HEAD_GROUP UNIQUEIDENTIFIER,
	FACULTY_ID UNIQUEIDENTIFIER NOT NULL,
);
GO

CREATE TABLE LESSONS
(
	GROUP_ID UNIQUEIDENTIFIER NOT NULL,
	PREPOD_ID UNIQUEIDENTIFIER NOT NULL,
	STUDY_ID CHAR(20) NOT NULL
);
GO

CREATE TABLE Prepods
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	LAST_NAME VARCHAR(120) NOT NULL,
	FIRST_NAME VARCHAR(120),
	FACULTY_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Faculty
);
GO

CREATE TABLE RATING
(
	ID UNIQUEIDENTIFIER NOT NULL,
	DATE DATE NOT NULL,
	VAL NUMERIC,
	STUDENT_ID UNIQUEIDENTIFIER NOT NULL,
	STUDY_ID CHAR(20) NOT NULL,
	PREPODS_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Prepods,
	IS_ABSENT VARCHAR(1) DEFAULT 'N',
	CONSTRAINT chkValue CHECK (VAL>3 AND VAL<=10)
);
GO

CREATE TABLE Students
(
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	LAST_NAME VARCHAR(260) NOT NULL,
	FIRST_NAME VARCHAR(230),
	GROUP_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES GROUPS
);
GO

CREATE TABLE STUDY_LOAD
(
	ID CHAR(20) NOT NULL PRIMARY KEY,
	hours NUMERIC,
	SUBJECT_UD UNIQUEIDENTIFIER NOT NULL,
	Type_STUDY_ID UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT chkStudyLoad CHECK (hours>=0)
);
GO

CREATE TABLE Subjects
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NAME VARCHAR(120) NOT NULL,
	FACULTY_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Faculty
);
GO

CREATE TABLE TYPE_STUDY_LOAD
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NAME VARCHAR(120) NOT NULL UNIQUE
);
GO

ALTER TABLE GROUPS
	ADD FOREIGN KEY (ID) REFERENCES Students;
ALTER TABLE GROUPS
	ADD FOREIGN KEY (HEAD_GROUP) REFERENCES Students;
ALTER TABLE GROUPS
	ADD FOREIGN KEY (FACULTY_ID) REFERENCES Faculty;
GO

ALTER TABLE LESSONS
	ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS;
ALTER TABLE LESSONS
	ADD FOREIGN KEY (PREPOD_ID) REFERENCES Prepods;
ALTER TABLE LESSONS
	ADD FOREIGN KEY (STUDY_ID) REFERENCES STUDY_LOAD;
GO

ALTER TABLE RATING			
	ADD FOREIGN KEY (STUDENT_ID) REFERENCES Students;
ALTER TABLE RATING			
	ADD FOREIGN KEY (STUDY_ID) REFERENCES STUDY_LOAD;
GO

ALTER TABLE STUDY_LOAD	
	ADD FOREIGN KEY (SUBJECT_UD) REFERENCES Subjects;
ALTER TABLE STUDY_LOAD
	ADD FOREIGN KEY (Type_STUDY_ID) REFERENCES TYPE_STUDY_LOAD;
GO